on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: dump input context
        env:
          INPUT_CONTEXT: ${{ toJSON(inputs) }}
        run: echo "$INPUT_CONTEXT"
      - name: Hello world action step
        id: hello
        uses: docker://ghcr.io/kyanny/zd-1427848-testing/zd-1427848-testing:v1
        with:
          who-to-greet: 'Mona the Octocat'
          args: ${{ inputs.who-to-greet }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
