on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: dump context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
          INPUT_CONTEXT: ${{ toJSON(inputs) }}
          ENV_CONTEXT: ${{ toJSON(env) }}
        run: |
          echo "$JOB_CONTEXT"
          echo "$INPUT_CONTEXT"
          echo "$ENV_CONTEXT"
      - name: Hello world action step
        id: hello
        uses: docker://ghcr.io/kyanny/zd-1427848-testing/zd-1427848-testing:v3
        with:
          who-to-greet: 'Mona the Octocat'
          foo: 'FOO'
          #args: ${{ inputs.who-to-greet }}
          args: "argument"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
