on: [push]

jobs:
  public_action_job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: kyanny/zd-1427848-testing@v4
  public_action_job_2:
    runs-on: ubuntu-latest
    steps:
      - uses: kyanny/zd-1427848-testing@v4
        with:
          who-to-greet: 'Mona the Octocat'
          who-to-goodbye: 'Lisa'
          args: "arg 1 2 3"

  dockerhub_image_job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ubuntu:latest
  dockerhub_image_job_2:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ubuntu:latest
        with:
          who-to-greet: 'Mona the Octocat'
          who-to-goodbye: 'Lisa'
          args: "arg 1 2 3"

  ghcr_image_job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ghcr.io/kyanny/zd-1427848-testing/zd-1427848-testing:v4
  ghcr_image_job_2:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ghcr.io/kyanny/zd-1427848-testing/zd-1427848-testing:v4
        with:
          who-to-greet: 'Mona the Octocat'
          who-to-goodbye: 'Lisa'
          args: "arg 1 2 3"
